In [2]:
import numpy as np
from PIL import Image
import os
from resizeimage import resizeimage

imageSize = (200, 200)
picsDir = os.listdir('./photos')
rootDir = './Photos/'
def filesfinder(directory):
    files_list = []

    for pic in directory:
        im = Image.open(rootDir + pic)

        files_list.append(im)

    length_of_list = len(files_list)

    return length_of_list, files_list
def resizing(image_size):
    resized_images = []
    for img in picsDir:
        image = Image.open(rootDir + img)
        image = resizeimage.resize_crop(image, image_size)
        # image.thumbnail(image_size)
        resized_images.append(image)

    return resized_images

def converttonumpyarray(list_of_resized_images):
    for image in list_of_resized_images:
        array1 = np.array(image).reshape(200, 200, 3)
        for img in list_of_resized_images:
            array2 = np.array(image).reshape(200, 200, 3)
            array1 = np.concatenate((array1, array2))
        break

    return array1
def main():
    # Finding files
    num_of_files, list_of_pics = filesfinder(picsDir)
    print('Number of files are : ', num_of_files)

    # Resizing pictures
    resized_images = resizing(imageSize)
    print("Resized images are: ")
    print(resized_images)

    # Converting to numpy array
    nparray = converttonumpyarray(resized_images)
    print("Numpy array of 20 images are:")
    print(nparray)

    return nparray

if __name__ == "__main__":
    main()


Number of files are :  3
Resized images are: 
[<PIL.Image.Image image mode=RGB size=200x200 at 0x211BCFB2710>, <PIL.Image.Image image mode=RGBA size=200x200 at 0x211BCFB2780>, <PIL.Image.Image image mode=RGBA size=200x200 at 0x211BCFB27F0>]
Numpy array of 20 images are:
[[[184 193 204]
  [179 190 198]
  [182 189 197]
  ...
  [205 209 209]
  [206 212 209]
  [207 212 208]]

 [[188 198 202]
  [188 195 202]
  [186 196 201]
  ...
  [205 212 212]
  [206 212 210]
  [210 214 210]]

 [[189 195 197]
  [196 200 202]
  [188 197 199]
  ...
  [210 215 212]
  [207 214 213]
  [212 216 213]]

 ...

 [[118 112 156]
  [120 102 146]
  [140 126 160]
  ...
  [194 209 203]
  [147 167 183]
  [ 98 104 150]]

 [[119 109 152]
  [135 122 154]
  [169 171 188]
  ...
  [168 188 194]
  [112 125 157]
  [ 79  81 139]]

 [[115 110 159]
  [139 125 163]
  [174 177 187]
  ...
  [114 130 159]
  [ 85  86 137]
  [ 83  81 135]]]
